#!/bin/sh
branch=$(git symbolic-ref HEAD 2>/dev/null | sed 's/refs\/heads\///')
if [ "$branch" = "main" ]; then
  echo "==========================================="
  echo "ERROR: No puedes pushear directamente a main."
  echo "Crea una rama y usa Pull Request."
  echo "==========================================="
  exit 1
fi
